---
- block:
  - name: Start cluster0 virtual machine
    vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      name: cluster0
      state: poweredon
    delegate_to: localhost

  - name: Check for cluster0 running
    wait_for:
      port: 22
      host: cluster0.example.com
      delay: 3
      timeout: 90


  rescue:
    - name: Force off cluster0 virtual machine
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        name: cluster0
        state: poweredoff
      delegate_to: localhost
      ignore_errors: yes

    - pause:
        seconds: 10

    - name: Try again
      include_tasks: loop_cluster0_vm.yml
