---
- block:
  - name: Start freebsd virtual machine
    vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      name: freebsd
      state: poweredon
    delegate_to: localhost

  - name: Check for freebsd running
    wait_for:
      port: 22
      host: freebsd.example.com
      delay: 3
      timeout: 90


  rescue:
    - name: Force off freebsd virtual machine
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        name: freebsd
        state: poweredoff
      delegate_to: localhost
      ignore_errors: yes

    - pause:
        seconds: 10

    - name: Try again
      include_tasks: loop_freebsd_vm.yml
