---
- block:
  - name: Start mssql virtual machine
    vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      name: mssql_db
      state: poweredon
    delegate_to: localhost

  - name: Check for mssql running
    wait_for:
      port: 22
      host: mssql.example.com
      delay: 3
      timeout: 90


  rescue:
    - name: Force off mssql virtual machine
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        name: mssql_db
        state: poweredoff
      delegate_to: localhost
      ignore_errors: yes

    - pause:
        seconds: 10

    - name: Try again
      include_tasks: loop_mssql_vm.yml
