---
- block:
  - name: Start tomcat virtual machine
    vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      name: tomcat
      state: poweredon
    delegate_to: localhost

  - name: Check for tomcat running
    wait_for:
      port: 8080
      host: tomcat.example.com
      delay: 3
      timeout: 90


  rescue:
    - name: Force off tomcat virtual machine
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        name: tomcat
        state: poweredoff
      delegate_to: localhost
      ignore_errors: yes

    - pause:
        seconds: 10

    - name: Try again
      include_tasks: loop_tomcat_vm.yml
