---
- block:
  - name: Start hana virtual machine
    vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      name: hana
      state: poweredon
    delegate_to: localhost

  - name: Check for hana running
    wait_for:
      port: 22
      host: hana.example.com
      delay: 3
      timeout: 90


  rescue:
    - name: Force off hana virtual machine
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        name: hana
        state: poweredoff
      delegate_to: localhost
      ignore_errors: yes

    - pause:
        seconds: 10

    - name: Try again
      include_tasks: loop_hana_vm.yml
