---
- hosts: workstation.example.com
  become: true
  tasks:
    - set_fact: 
        conn_ok: false

    - name: Wait for NFS to be available
      wait_for:
        port: 2049
        host: storage.example.com
        delay: 10
        timeout: 1200

    - name: Wait for ESX and vCenter servers port 443 to be available
      wait_for:
        port: 443
        host: "{{ item }}"
        delay: 10
        timeout: 1200
      with_items:
        - esx1.example.com
        - esx2.example.com
        - vcenter.example.com

    - name: Wait for vCenter port 9443 to be available
      wait_for:
        port: 9443
        host: vcenter.example.com
        delay: 10
        timeout: 1200

    - name: Wait for vCenter port 5480 to be available
      wait_for:
        port: 5480
        host: vcenter.example.com
        delay: 10
        timeout: 1200

    - name: Wait for vCenter port 8084 to be available
      wait_for:
        port: 8084
        host: vcenter.example.com
        delay: 10
        timeout: 1200

    - name: Start db
      include_tasks: loops/loop_db_vm.yml

    - name: Start jboss0
      include_tasks: loops/loop_jboss0_vm.yml

    - name: Start jboss1
      include_tasks: loops/loop_jboss1_vm.yml

    - name: Start lb
      include_tasks: loops/loop_lb_vm.yml

    - name: Start tomcat
      include_tasks: loops/loop_tomcat_vm.yml

    - name: Start weblogic
      include_tasks: loops/loop_weblogic_vm.yml

    - name: Start websphere
      include_tasks: loops/loop_websphere_vm.yml

    - name: Start FreeBSD
      include_tasks: loops/loop_freebsd_vm.yml

    - name: Start HANA
      include_tasks: loops/loop_hana_vm.yml

    - name: Start MS SQL Server
      include_tasks: loops/loop_mssql_vm.yml

    - name: Start Oracle DB Server
      include_tasks: loops/loop_oracledb_vm.yml

    - name: Start Cluster0
      include_tasks: loops/loop_cluster0_vm.yml

    - name: Start Cluster1
      include_tasks: loops/loop_cluster1_vm.yml

    - name: Check powerstate on VMs
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        name: "{{ item }}"
        state: poweredon
      delegate_to: localhost
      ignore_errors: yes
      with_items:
        - db
        - jboss0
        - jboss1
        - lb
        - tomcat
        - weblogic
        - websphere
        - freebsd
        - hana
        - mssql_db
        - oracle_db
        - wmssql_db
        - cluster0
        - cluster1
