---
- hosts: workstation.example.com
  become: true
  tasks:
    - set_fact: 
        conn_ok: false

    - name: Shutdown gracefully VMs
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        name: "{{ item }}"
        state: shutdownguest
      delegate_to: localhost
      ignore_errors: yes
      state_change_timeout: 3
      with_items:
        - hana
        - mssql_db
        - oracle_db
        - wmssql_db
        - tomcat
        - weblogic
        - websphere
        - db
        - jboss0
        - jboss1
        - lb
        - freebsd
